name: 'Notification event to datadog'
description: 'Notify datadog with events'
branding:
  icon: message-square
  color: orange
inputs:
  datadog-api-key:
    description: api key
    required: true
  parsley-environment:
    description: env description
    required: true
  parsley-componentname:
    description: component name
    required: true
outputs:
  datadog-response:
    description: Datadog response

runs:
  using: 'node12'
  main: 'index.js'
